baseURL = "https://someusername1.github.io/"
languageCode = "en-us"
title = "Fabian H. Klopfer"

[params]
  description = "Software Engineer — Neuroscience & Database Systems"
  github = "https://github.com/SomeUserName1"
  linkedin = "https://www.linkedin.com/in/someusername1/"
  email = "fabian.klopfer@ieee.org"
